version: '3.8'
services:
  masterdatadb:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: masterdatadb
    ports:
      - '5432:5432'
    volumes:
      - masterdata_db_data:/var/lib/postgresql/data

  test_masterdatadb:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: testmasterdatadb
    ports:
      - '5433:5432'
    volumes:
      - test_masterdata_db_data:/var/lib/postgresql/data

volumes:
  masterdata_db_data:
  test_masterdata_db_data:
