#!/usr/bin/env bash

set -e

./build.sh
rm -rf docs/src/content/docs/{backend,frontend,domain}
pnpm lect-effect/docs:generate
# Hide autogenerated module index pages from end-user navigation while keeping them for Starlight.
for section in backend frontend domain; do
	src="docs/src/content/docs/${section}/modules/index.md"
	dst="docs/src/content/docs/${section}/modules/_index.md"
	if [ -f "$src" ]; then
		mv "$src" "$dst"
	fi
done
pnpm -C docs dev -- "$@"
